---
os: linux
dist: bionic
language: generic
services:
  - xvfb
cache:
  directories:
    - packer_cache
install:
  - sudo rm -f $(which packer)  # delete the currently installed packer script
  - wget -qO- https://raw.githubusercontent.com/sprat/install-scripts/master/install_virtualbox.sh | sudo bash
  - wget -qO- https://raw.githubusercontent.com/sprat/install-scripts/master/install_hashicorp_packages.sh | sudo bash -s vagrant packer
script:
  - ./build 20.04/server.json
