---
os: linux
dist: bionic
language: minimal
cache:
  directories:
    - packer_cache
install:
  - sudo ./install/virtualbox.sh
  - sudo ./install/vagrant.sh
  - sudo ./install/packer.sh
script:
  - ./build ubuntu-server-20.04.json
