---
os: linux
dist: bionic
language: minimal
cache:
  directories:
    - packer_cache
install:
  - sudo ./install/virtualbox.sh
  - sudo ./install/vagrant.sh
  - sudo ./install/packer.sh
  - vagrant version
  - packer version
script:
  - ./build focal-server.json || cat *.log && exit 1
