---
os: linux
dist: bionic
language: generic
services:
  - xvfb
cache:
  directories:
    - packer_cache
install:
  - sudo rm -f $(which packer)  # delete the currently installed packer script
  - sudo ./install/virtualbox.sh
  - sudo ./install/vagrant_packer.sh
  - vboxmanage --version
  - vagrant version
  - packer version
script:
  - ./build focal-server.json
