#!/bin/bash
if [ "$#" -lt 1 ]; then
    echo "Usage: $0 VAR_FILE [OPTIONS...]"
    echo "where VAR_FILE is focal-server.json, focal-desktop.json, ..."
    exit 1
fi

PACKER_LOG=1 packer build -var-file=$* packer/template.json
